/*
otp OTP API

Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API.  Errors are always `{\"error\": {\"type\", \"message\", \"details\"?}}`.  When routing picks WhatsApp the code is not sent yet: the send response carries an `action_url` (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. Verification is identical on every channel.  If your app uses one of the mobile SDKs, the device verifies against the client API and receives a `verification_token` instead of a result. Exchange that token here, with your server key (`POST /verifications/exchange`), to learn which recipient was verified. What an app tells your backend about its own verification is unverifiable, so the token is the whole security model.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package otp

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VerificationExchangeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerificationExchangeRequest{}

// VerificationExchangeRequest struct for VerificationExchangeRequest
type VerificationExchangeRequest struct {
	// The verification_token your app received from POST /client/otp/verify.
	VerificationToken string `json:"verification_token"`
}

type _VerificationExchangeRequest VerificationExchangeRequest

// NewVerificationExchangeRequest instantiates a new VerificationExchangeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerificationExchangeRequest(verificationToken string) *VerificationExchangeRequest {
	this := VerificationExchangeRequest{}
	this.VerificationToken = verificationToken
	return &this
}

// NewVerificationExchangeRequestWithDefaults instantiates a new VerificationExchangeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerificationExchangeRequestWithDefaults() *VerificationExchangeRequest {
	this := VerificationExchangeRequest{}
	return &this
}

// GetVerificationToken returns the VerificationToken field value
func (o *VerificationExchangeRequest) GetVerificationToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VerificationToken
}

// GetVerificationTokenOk returns a tuple with the VerificationToken field value
// and a boolean to check if the value has been set.
func (o *VerificationExchangeRequest) GetVerificationTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerificationToken, true
}

// SetVerificationToken sets field value
func (o *VerificationExchangeRequest) SetVerificationToken(v string) {
	o.VerificationToken = v
}

func (o VerificationExchangeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerificationExchangeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["verification_token"] = o.VerificationToken
	return toSerialize, nil
}

func (o *VerificationExchangeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"verification_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerificationExchangeRequest := _VerificationExchangeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVerificationExchangeRequest)

	if err != nil {
		return err
	}

	*o = VerificationExchangeRequest(varVerificationExchangeRequest)

	return err
}

type NullableVerificationExchangeRequest struct {
	value *VerificationExchangeRequest
	isSet bool
}

func (v NullableVerificationExchangeRequest) Get() *VerificationExchangeRequest {
	return v.value
}

func (v *NullableVerificationExchangeRequest) Set(val *VerificationExchangeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVerificationExchangeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVerificationExchangeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerificationExchangeRequest(val *VerificationExchangeRequest) *NullableVerificationExchangeRequest {
	return &NullableVerificationExchangeRequest{value: val, isSet: true}
}

func (v NullableVerificationExchangeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerificationExchangeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


