/*
otp OTP API

Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package otp

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SendRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendRequest{}

// SendRequest struct for SendRequest
type SendRequest struct {
	// Phone number in E.164 (e.g. +14155552671) or an email address.
	Recipient string `json:"recipient"`
	// Message language, e.g. \"en\" or \"tr\".
	Locale *string `json:"locale,omitempty"`
}

type _SendRequest SendRequest

// NewSendRequest instantiates a new SendRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendRequest(recipient string) *SendRequest {
	this := SendRequest{}
	this.Recipient = recipient
	return &this
}

// NewSendRequestWithDefaults instantiates a new SendRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendRequestWithDefaults() *SendRequest {
	this := SendRequest{}
	return &this
}

// GetRecipient returns the Recipient field value
func (o *SendRequest) GetRecipient() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value
// and a boolean to check if the value has been set.
func (o *SendRequest) GetRecipientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Recipient, true
}

// SetRecipient sets field value
func (o *SendRequest) SetRecipient(v string) {
	o.Recipient = v
}

// GetLocale returns the Locale field value if set, zero value otherwise.
func (o *SendRequest) GetLocale() string {
	if o == nil || IsNil(o.Locale) {
		var ret string
		return ret
	}
	return *o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendRequest) GetLocaleOk() (*string, bool) {
	if o == nil || IsNil(o.Locale) {
		return nil, false
	}
	return o.Locale, true
}

// HasLocale returns a boolean if a field has been set.
func (o *SendRequest) HasLocale() bool {
	if o != nil && !IsNil(o.Locale) {
		return true
	}

	return false
}

// SetLocale gets a reference to the given string and assigns it to the Locale field.
func (o *SendRequest) SetLocale(v string) {
	o.Locale = &v
}

func (o SendRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["recipient"] = o.Recipient
	if !IsNil(o.Locale) {
		toSerialize["locale"] = o.Locale
	}
	return toSerialize, nil
}

func (o *SendRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"recipient",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSendRequest := _SendRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSendRequest)

	if err != nil {
		return err
	}

	*o = SendRequest(varSendRequest)

	return err
}

type NullableSendRequest struct {
	value *SendRequest
	isSet bool
}

func (v NullableSendRequest) Get() *SendRequest {
	return v.value
}

func (v *NullableSendRequest) Set(val *SendRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSendRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSendRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendRequest(val *SendRequest) *NullableSendRequest {
	return &NullableSendRequest{value: val, isSet: true}
}

func (v NullableSendRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


