/*
otp OTP API

Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package otp

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResendRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResendRequest{}

// ResendRequest struct for ResendRequest
type ResendRequest struct {
	OtpId string `json:"otp_id"`
	// Move this OTP onto a specific channel, e.g. \"sms\" when the recipient has no WhatsApp. The channel must be enabled for your app and the recipient. Omit to advance to the next channel in your routing order. 
	Channel NullableString `json:"channel,omitempty"`
}

type _ResendRequest ResendRequest

// NewResendRequest instantiates a new ResendRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResendRequest(otpId string) *ResendRequest {
	this := ResendRequest{}
	this.OtpId = otpId
	return &this
}

// NewResendRequestWithDefaults instantiates a new ResendRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResendRequestWithDefaults() *ResendRequest {
	this := ResendRequest{}
	return &this
}

// GetOtpId returns the OtpId field value
func (o *ResendRequest) GetOtpId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OtpId
}

// GetOtpIdOk returns a tuple with the OtpId field value
// and a boolean to check if the value has been set.
func (o *ResendRequest) GetOtpIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OtpId, true
}

// SetOtpId sets field value
func (o *ResendRequest) SetOtpId(v string) {
	o.OtpId = v
}

// GetChannel returns the Channel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResendRequest) GetChannel() string {
	if o == nil || IsNil(o.Channel.Get()) {
		var ret string
		return ret
	}
	return *o.Channel.Get()
}

// GetChannelOk returns a tuple with the Channel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResendRequest) GetChannelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Channel.Get(), o.Channel.IsSet()
}

// HasChannel returns a boolean if a field has been set.
func (o *ResendRequest) HasChannel() bool {
	if o != nil && o.Channel.IsSet() {
		return true
	}

	return false
}

// SetChannel gets a reference to the given NullableString and assigns it to the Channel field.
func (o *ResendRequest) SetChannel(v string) {
	o.Channel.Set(&v)
}
// SetChannelNil sets the value for Channel to be an explicit nil
func (o *ResendRequest) SetChannelNil() {
	o.Channel.Set(nil)
}

// UnsetChannel ensures that no value is present for Channel, not even an explicit nil
func (o *ResendRequest) UnsetChannel() {
	o.Channel.Unset()
}

func (o ResendRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResendRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["otp_id"] = o.OtpId
	if o.Channel.IsSet() {
		toSerialize["channel"] = o.Channel.Get()
	}
	return toSerialize, nil
}

func (o *ResendRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"otp_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResendRequest := _ResendRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResendRequest)

	if err != nil {
		return err
	}

	*o = ResendRequest(varResendRequest)

	return err
}

type NullableResendRequest struct {
	value *ResendRequest
	isSet bool
}

func (v NullableResendRequest) Get() *ResendRequest {
	return v.value
}

func (v *NullableResendRequest) Set(val *ResendRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableResendRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableResendRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResendRequest(val *ResendRequest) *NullableResendRequest {
	return &NullableResendRequest{value: val, isSet: true}
}

func (v NullableResendRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResendRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


