/*
otp OTP API

Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API.  Errors are always `{\"error\": {\"type\", \"message\", \"details\"?}}`.  When routing picks WhatsApp the code is not sent yet: the send response carries an `action_url` (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. Verification is identical on every channel.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package otp

import (
	"encoding/json"
	"fmt"
)

// Channel Channel the OTP was dispatched on; null until routed.
type Channel string

// List of Channel
const (
	SMS Channel = "sms"
	WHATSAPP Channel = "whatsapp"
	EMAIL Channel = "email"
	TELEGRAM Channel = "telegram"
)

// All allowed values of Channel enum
var AllowedChannelEnumValues = []Channel{
	"sms",
	"whatsapp",
	"email",
	"telegram",
}

func (v *Channel) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Channel(value)
	for _, existing := range AllowedChannelEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Channel", value)
}

// NewChannelFromValue returns a pointer to a valid Channel
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewChannelFromValue(v string) (*Channel, error) {
	ev := Channel(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Channel: valid values are %v", v, AllowedChannelEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Channel) IsValid() bool {
	for _, existing := range AllowedChannelEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Channel value
func (v Channel) Ptr() *Channel {
	return &v
}

type NullableChannel struct {
	value *Channel
	isSet bool
}

func (v NullableChannel) Get() *Channel {
	return v.value
}

func (v *NullableChannel) Set(val *Channel) {
	v.value = val
	v.isSet = true
}

func (v NullableChannel) IsSet() bool {
	return v.isSet
}

func (v *NullableChannel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannel(val *Channel) *NullableChannel {
	return &NullableChannel{value: val, isSet: true}
}

func (v NullableChannel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

