/*
otp OTP API

Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API.  Errors are always `{\"error\": {\"type\", \"message\", \"details\"?}}`.  When routing picks WhatsApp the code is not sent yet: the send response carries an `action_url` (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. Verification is identical on every channel.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package otp

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OtpResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OtpResponse{}

// OtpResponse struct for OtpResponse
type OtpResponse struct {
	OtpId string `json:"otp_id"`
	Status Status `json:"status"`
	// Channel the OTP was dispatched on; null until routed.
	Channel NullableChannel `json:"channel"`
	// Recipient with the middle digits masked.
	MaskedRecipient string `json:"masked_recipient"`
	// WhatsApp link the user opens to receive the code: they send us the prefilled message and we reply with the code over WhatsApp, then they enter it and you call POST /otp/verify. Present only when dispatched on the whatsapp channel; null otherwise.
	ActionUrl NullableString `json:"action_url,omitempty"`
}

type _OtpResponse OtpResponse

// NewOtpResponse instantiates a new OtpResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOtpResponse(otpId string, status Status, channel NullableChannel, maskedRecipient string) *OtpResponse {
	this := OtpResponse{}
	this.OtpId = otpId
	this.Status = status
	this.Channel = channel
	this.MaskedRecipient = maskedRecipient
	return &this
}

// NewOtpResponseWithDefaults instantiates a new OtpResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOtpResponseWithDefaults() *OtpResponse {
	this := OtpResponse{}
	return &this
}

// GetOtpId returns the OtpId field value
func (o *OtpResponse) GetOtpId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OtpId
}

// GetOtpIdOk returns a tuple with the OtpId field value
// and a boolean to check if the value has been set.
func (o *OtpResponse) GetOtpIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OtpId, true
}

// SetOtpId sets field value
func (o *OtpResponse) SetOtpId(v string) {
	o.OtpId = v
}

// GetStatus returns the Status field value
func (o *OtpResponse) GetStatus() Status {
	if o == nil {
		var ret Status
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *OtpResponse) GetStatusOk() (*Status, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *OtpResponse) SetStatus(v Status) {
	o.Status = v
}

// GetChannel returns the Channel field value
// If the value is explicit nil, the zero value for Channel will be returned
func (o *OtpResponse) GetChannel() Channel {
	if o == nil || o.Channel.Get() == nil {
		var ret Channel
		return ret
	}

	return *o.Channel.Get()
}

// GetChannelOk returns a tuple with the Channel field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OtpResponse) GetChannelOk() (*Channel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Channel.Get(), o.Channel.IsSet()
}

// SetChannel sets field value
func (o *OtpResponse) SetChannel(v Channel) {
	o.Channel.Set(&v)
}

// GetMaskedRecipient returns the MaskedRecipient field value
func (o *OtpResponse) GetMaskedRecipient() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MaskedRecipient
}

// GetMaskedRecipientOk returns a tuple with the MaskedRecipient field value
// and a boolean to check if the value has been set.
func (o *OtpResponse) GetMaskedRecipientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaskedRecipient, true
}

// SetMaskedRecipient sets field value
func (o *OtpResponse) SetMaskedRecipient(v string) {
	o.MaskedRecipient = v
}

// GetActionUrl returns the ActionUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OtpResponse) GetActionUrl() string {
	if o == nil || IsNil(o.ActionUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ActionUrl.Get()
}

// GetActionUrlOk returns a tuple with the ActionUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OtpResponse) GetActionUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActionUrl.Get(), o.ActionUrl.IsSet()
}

// HasActionUrl returns a boolean if a field has been set.
func (o *OtpResponse) HasActionUrl() bool {
	if o != nil && o.ActionUrl.IsSet() {
		return true
	}

	return false
}

// SetActionUrl gets a reference to the given NullableString and assigns it to the ActionUrl field.
func (o *OtpResponse) SetActionUrl(v string) {
	o.ActionUrl.Set(&v)
}
// SetActionUrlNil sets the value for ActionUrl to be an explicit nil
func (o *OtpResponse) SetActionUrlNil() {
	o.ActionUrl.Set(nil)
}

// UnsetActionUrl ensures that no value is present for ActionUrl, not even an explicit nil
func (o *OtpResponse) UnsetActionUrl() {
	o.ActionUrl.Unset()
}

func (o OtpResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OtpResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["otp_id"] = o.OtpId
	toSerialize["status"] = o.Status
	toSerialize["channel"] = o.Channel.Get()
	toSerialize["masked_recipient"] = o.MaskedRecipient
	if o.ActionUrl.IsSet() {
		toSerialize["action_url"] = o.ActionUrl.Get()
	}
	return toSerialize, nil
}

func (o *OtpResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"otp_id",
		"status",
		"channel",
		"masked_recipient",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOtpResponse := _OtpResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOtpResponse)

	if err != nil {
		return err
	}

	*o = OtpResponse(varOtpResponse)

	return err
}

type NullableOtpResponse struct {
	value *OtpResponse
	isSet bool
}

func (v NullableOtpResponse) Get() *OtpResponse {
	return v.value
}

func (v *NullableOtpResponse) Set(val *OtpResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOtpResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOtpResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOtpResponse(val *OtpResponse) *NullableOtpResponse {
	return &NullableOtpResponse{value: val, isSet: true}
}

func (v NullableOtpResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOtpResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


