/*
otp OTP API

Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package otp

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VerifyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyRequest{}

// VerifyRequest struct for VerifyRequest
type VerifyRequest struct {
	OtpId string `json:"otp_id"`
	Code string `json:"code"`
}

type _VerifyRequest VerifyRequest

// NewVerifyRequest instantiates a new VerifyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyRequest(otpId string, code string) *VerifyRequest {
	this := VerifyRequest{}
	this.OtpId = otpId
	this.Code = code
	return &this
}

// NewVerifyRequestWithDefaults instantiates a new VerifyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyRequestWithDefaults() *VerifyRequest {
	this := VerifyRequest{}
	return &this
}

// GetOtpId returns the OtpId field value
func (o *VerifyRequest) GetOtpId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OtpId
}

// GetOtpIdOk returns a tuple with the OtpId field value
// and a boolean to check if the value has been set.
func (o *VerifyRequest) GetOtpIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OtpId, true
}

// SetOtpId sets field value
func (o *VerifyRequest) SetOtpId(v string) {
	o.OtpId = v
}

// GetCode returns the Code field value
func (o *VerifyRequest) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *VerifyRequest) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *VerifyRequest) SetCode(v string) {
	o.Code = v
}

func (o VerifyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["otp_id"] = o.OtpId
	toSerialize["code"] = o.Code
	return toSerialize, nil
}

func (o *VerifyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"otp_id",
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerifyRequest := _VerifyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVerifyRequest)

	if err != nil {
		return err
	}

	*o = VerifyRequest(varVerifyRequest)

	return err
}

type NullableVerifyRequest struct {
	value *VerifyRequest
	isSet bool
}

func (v NullableVerifyRequest) Get() *VerifyRequest {
	return v.value
}

func (v *NullableVerifyRequest) Set(val *VerifyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyRequest(val *VerifyRequest) *NullableVerifyRequest {
	return &NullableVerifyRequest{value: val, isSet: true}
}

func (v NullableVerifyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


