/*
otp OTP API

Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package otp

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OtpStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OtpStatusResponse{}

// OtpStatusResponse struct for OtpStatusResponse
type OtpStatusResponse struct {
	OtpId string `json:"otp_id"`
	Status Status `json:"status"`
	MaskedRecipient string `json:"masked_recipient"`
}

type _OtpStatusResponse OtpStatusResponse

// NewOtpStatusResponse instantiates a new OtpStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOtpStatusResponse(otpId string, status Status, maskedRecipient string) *OtpStatusResponse {
	this := OtpStatusResponse{}
	this.OtpId = otpId
	this.Status = status
	this.MaskedRecipient = maskedRecipient
	return &this
}

// NewOtpStatusResponseWithDefaults instantiates a new OtpStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOtpStatusResponseWithDefaults() *OtpStatusResponse {
	this := OtpStatusResponse{}
	return &this
}

// GetOtpId returns the OtpId field value
func (o *OtpStatusResponse) GetOtpId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OtpId
}

// GetOtpIdOk returns a tuple with the OtpId field value
// and a boolean to check if the value has been set.
func (o *OtpStatusResponse) GetOtpIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OtpId, true
}

// SetOtpId sets field value
func (o *OtpStatusResponse) SetOtpId(v string) {
	o.OtpId = v
}

// GetStatus returns the Status field value
func (o *OtpStatusResponse) GetStatus() Status {
	if o == nil {
		var ret Status
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *OtpStatusResponse) GetStatusOk() (*Status, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *OtpStatusResponse) SetStatus(v Status) {
	o.Status = v
}

// GetMaskedRecipient returns the MaskedRecipient field value
func (o *OtpStatusResponse) GetMaskedRecipient() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MaskedRecipient
}

// GetMaskedRecipientOk returns a tuple with the MaskedRecipient field value
// and a boolean to check if the value has been set.
func (o *OtpStatusResponse) GetMaskedRecipientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaskedRecipient, true
}

// SetMaskedRecipient sets field value
func (o *OtpStatusResponse) SetMaskedRecipient(v string) {
	o.MaskedRecipient = v
}

func (o OtpStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OtpStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["otp_id"] = o.OtpId
	toSerialize["status"] = o.Status
	toSerialize["masked_recipient"] = o.MaskedRecipient
	return toSerialize, nil
}

func (o *OtpStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"otp_id",
		"status",
		"masked_recipient",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOtpStatusResponse := _OtpStatusResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOtpStatusResponse)

	if err != nil {
		return err
	}

	*o = OtpStatusResponse(varOtpStatusResponse)

	return err
}

type NullableOtpStatusResponse struct {
	value *OtpStatusResponse
	isSet bool
}

func (v NullableOtpStatusResponse) Get() *OtpStatusResponse {
	return v.value
}

func (v *NullableOtpStatusResponse) Set(val *OtpStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOtpStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOtpStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOtpStatusResponse(val *OtpStatusResponse) *NullableOtpStatusResponse {
	return &NullableOtpStatusResponse{value: val, isSet: true}
}

func (v NullableOtpStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOtpStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


