/*
otp OTP API

Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API.  Errors are always `{\"error\": {\"type\", \"message\", \"details\"?}}`.  When routing picks WhatsApp the code is not sent yet: the send response carries an `action_url` (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. Verification is identical on every channel.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package otp

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ErrorBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ErrorBody{}

// ErrorBody struct for ErrorBody
type ErrorBody struct {
	// Machine-readable error class, e.g. \"OtpNotFoundError\".
	Type string `json:"type"`
	// Human-readable message. Safe to log; never contains the OTP code.
	Message string `json:"message"`
	// Structured context, present on validation errors ({loc, msg, type} per field) and a few domain errors.
	Details map[string]interface{} `json:"details,omitempty"`
}

type _ErrorBody ErrorBody

// NewErrorBody instantiates a new ErrorBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewErrorBody(type_ string, message string) *ErrorBody {
	this := ErrorBody{}
	this.Type = type_
	this.Message = message
	return &this
}

// NewErrorBodyWithDefaults instantiates a new ErrorBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewErrorBodyWithDefaults() *ErrorBody {
	this := ErrorBody{}
	return &this
}

// GetType returns the Type field value
func (o *ErrorBody) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ErrorBody) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ErrorBody) SetType(v string) {
	o.Type = v
}

// GetMessage returns the Message field value
func (o *ErrorBody) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ErrorBody) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ErrorBody) SetMessage(v string) {
	o.Message = v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *ErrorBody) GetDetails() map[string]interface{} {
	if o == nil || IsNil(o.Details) {
		var ret map[string]interface{}
		return ret
	}
	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ErrorBody) GetDetailsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Details) {
		return map[string]interface{}{}, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *ErrorBody) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given map[string]interface{} and assigns it to the Details field.
func (o *ErrorBody) SetDetails(v map[string]interface{}) {
	o.Details = v
}

func (o ErrorBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ErrorBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["message"] = o.Message
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	return toSerialize, nil
}

func (o *ErrorBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varErrorBody := _ErrorBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varErrorBody)

	if err != nil {
		return err
	}

	*o = ErrorBody(varErrorBody)

	return err
}

type NullableErrorBody struct {
	value *ErrorBody
	isSet bool
}

func (v NullableErrorBody) Get() *ErrorBody {
	return v.value
}

func (v *NullableErrorBody) Set(val *ErrorBody) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorBody) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorBody(val *ErrorBody) *NullableErrorBody {
	return &NullableErrorBody{value: val, isSet: true}
}

func (v NullableErrorBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


