/*
otp OTP API

Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API.  Errors are always `{\"error\": {\"type\", \"message\", \"details\"?}}`.  When routing picks WhatsApp the code is not sent yet: the send response carries an `action_url` (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. Verification is identical on every channel.  If your app uses one of the mobile SDKs, the device verifies against the client API and receives a `verification_token` instead of a result. Exchange that token here, with your server key (`POST /verifications/exchange`), to learn which recipient was verified. What an app tells your backend about its own verification is unverifiable, so the token is the whole security model.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package otp

import (
	"encoding/json"
	"fmt"
)

// RecipientType the model 'RecipientType'
type RecipientType string

// List of RecipientType
const (
	PHONE RecipientType = "phone"
	EMAIL RecipientType = "email"
)

// All allowed values of RecipientType enum
var AllowedRecipientTypeEnumValues = []RecipientType{
	"phone",
	"email",
}

func (v *RecipientType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RecipientType(value)
	for _, existing := range AllowedRecipientTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RecipientType", value)
}

// NewRecipientTypeFromValue returns a pointer to a valid RecipientType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRecipientTypeFromValue(v string) (*RecipientType, error) {
	ev := RecipientType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RecipientType: valid values are %v", v, AllowedRecipientTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RecipientType) IsValid() bool {
	for _, existing := range AllowedRecipientTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RecipientType value
func (v RecipientType) Ptr() *RecipientType {
	return &v
}

type NullableRecipientType struct {
	value *RecipientType
	isSet bool
}

func (v NullableRecipientType) Get() *RecipientType {
	return v.value
}

func (v *NullableRecipientType) Set(val *RecipientType) {
	v.value = val
	v.isSet = true
}

func (v NullableRecipientType) IsSet() bool {
	return v.isSet
}

func (v *NullableRecipientType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecipientType(val *RecipientType) *NullableRecipientType {
	return &NullableRecipientType{value: val, isSet: true}
}

func (v NullableRecipientType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecipientType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

