/*
otp OTP API

Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API.  Errors are always `{\"error\": {\"type\", \"message\", \"details\"?}}`.  When routing picks WhatsApp the code is not sent yet: the send response carries an `action_url` (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. Verification is identical on every channel.  If your app uses one of the mobile SDKs, the device verifies against the client API and receives a `verification_token` instead of a result. Exchange that token here, with your server key (`POST /verifications/exchange`), to learn which recipient was verified. What an app tells your backend about its own verification is unverifiable, so the token is the whole security model.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package otp

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the VerificationExchangeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerificationExchangeResponse{}

// VerificationExchangeResponse struct for VerificationExchangeResponse
type VerificationExchangeResponse struct {
	// The OTP this verification belongs to.
	OtpId string `json:"otp_id"`
	// The recipient that was verified, in full. This is the answer the device could not be trusted to give you.
	Recipient string `json:"recipient"`
	RecipientType RecipientType `json:"recipient_type"`
	// Channel the verified code was delivered on.
	Channel NullableChannel `json:"channel"`
	// When the end user entered the correct code.
	VerifiedAt time.Time `json:"verified_at"`
}

type _VerificationExchangeResponse VerificationExchangeResponse

// NewVerificationExchangeResponse instantiates a new VerificationExchangeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerificationExchangeResponse(otpId string, recipient string, recipientType RecipientType, channel NullableChannel, verifiedAt time.Time) *VerificationExchangeResponse {
	this := VerificationExchangeResponse{}
	this.OtpId = otpId
	this.Recipient = recipient
	this.RecipientType = recipientType
	this.Channel = channel
	this.VerifiedAt = verifiedAt
	return &this
}

// NewVerificationExchangeResponseWithDefaults instantiates a new VerificationExchangeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerificationExchangeResponseWithDefaults() *VerificationExchangeResponse {
	this := VerificationExchangeResponse{}
	return &this
}

// GetOtpId returns the OtpId field value
func (o *VerificationExchangeResponse) GetOtpId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OtpId
}

// GetOtpIdOk returns a tuple with the OtpId field value
// and a boolean to check if the value has been set.
func (o *VerificationExchangeResponse) GetOtpIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OtpId, true
}

// SetOtpId sets field value
func (o *VerificationExchangeResponse) SetOtpId(v string) {
	o.OtpId = v
}

// GetRecipient returns the Recipient field value
func (o *VerificationExchangeResponse) GetRecipient() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value
// and a boolean to check if the value has been set.
func (o *VerificationExchangeResponse) GetRecipientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Recipient, true
}

// SetRecipient sets field value
func (o *VerificationExchangeResponse) SetRecipient(v string) {
	o.Recipient = v
}

// GetRecipientType returns the RecipientType field value
func (o *VerificationExchangeResponse) GetRecipientType() RecipientType {
	if o == nil {
		var ret RecipientType
		return ret
	}

	return o.RecipientType
}

// GetRecipientTypeOk returns a tuple with the RecipientType field value
// and a boolean to check if the value has been set.
func (o *VerificationExchangeResponse) GetRecipientTypeOk() (*RecipientType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecipientType, true
}

// SetRecipientType sets field value
func (o *VerificationExchangeResponse) SetRecipientType(v RecipientType) {
	o.RecipientType = v
}

// GetChannel returns the Channel field value
// If the value is explicit nil, the zero value for Channel will be returned
func (o *VerificationExchangeResponse) GetChannel() Channel {
	if o == nil || o.Channel.Get() == nil {
		var ret Channel
		return ret
	}

	return *o.Channel.Get()
}

// GetChannelOk returns a tuple with the Channel field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VerificationExchangeResponse) GetChannelOk() (*Channel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Channel.Get(), o.Channel.IsSet()
}

// SetChannel sets field value
func (o *VerificationExchangeResponse) SetChannel(v Channel) {
	o.Channel.Set(&v)
}

// GetVerifiedAt returns the VerifiedAt field value
func (o *VerificationExchangeResponse) GetVerifiedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.VerifiedAt
}

// GetVerifiedAtOk returns a tuple with the VerifiedAt field value
// and a boolean to check if the value has been set.
func (o *VerificationExchangeResponse) GetVerifiedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerifiedAt, true
}

// SetVerifiedAt sets field value
func (o *VerificationExchangeResponse) SetVerifiedAt(v time.Time) {
	o.VerifiedAt = v
}

func (o VerificationExchangeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerificationExchangeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["otp_id"] = o.OtpId
	toSerialize["recipient"] = o.Recipient
	toSerialize["recipient_type"] = o.RecipientType
	toSerialize["channel"] = o.Channel.Get()
	toSerialize["verified_at"] = o.VerifiedAt
	return toSerialize, nil
}

func (o *VerificationExchangeResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"otp_id",
		"recipient",
		"recipient_type",
		"channel",
		"verified_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerificationExchangeResponse := _VerificationExchangeResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVerificationExchangeResponse)

	if err != nil {
		return err
	}

	*o = VerificationExchangeResponse(varVerificationExchangeResponse)

	return err
}

type NullableVerificationExchangeResponse struct {
	value *VerificationExchangeResponse
	isSet bool
}

func (v NullableVerificationExchangeResponse) Get() *VerificationExchangeResponse {
	return v.value
}

func (v *NullableVerificationExchangeResponse) Set(val *VerificationExchangeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVerificationExchangeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVerificationExchangeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerificationExchangeResponse(val *VerificationExchangeResponse) *NullableVerificationExchangeResponse {
	return &NullableVerificationExchangeResponse{value: val, isSet: true}
}

func (v NullableVerificationExchangeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerificationExchangeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


